### ISSUE TITLE
Take statistics from brew into account

### ISSUE THREAD

**Issue by corneliusweig** [corneliusweig/krew-index-tracker#4]
Homebrew now packages `krew` and bypasses this statistics collection (https://github.com/Homebrew/homebrew-core/pull/49428).

For a more accurate picture it would be good to take up the statistics from homebrew. For example, there are monthly download counts in

```
curl https://formulae.brew.sh/api/formula/krew.json | jq .
```

There are two problems here:
1. The best we can extract from there is a moving average over the past 30 days. This makes it impossible to calculate accurate download counts for the last 24 hours.

2. It is difficult to map the download counts to the exact version that was installed.

---

To get a rough picture, we can do the following:

1. Estimate daily downloads by `30d-average / 30`.
2. Always attribute downloads to the latest krew version.

cc @ahmetb

**Comment by ahmetb** [comment]
It's unlikely we'll be able to tell download counts in a particular day with this data. But at least we can monitor our 365d installs over time.

It'd be better if we record everything Homebrew Analtyics API provides in a separate table. We can start to make sense of it later. Sadly it'll be a separate chart in the stats dashboard. :(

**Comment by corneliusweig** [comment]
Yeah, probably better to collect raw data instead of trying to be smart upfront.

**Comment by corneliusweig** [comment]
Homebrew statistics are now scraped every day and dumped into a separate BQ table.
